function windTrace(kind,s,r){
 const t=terrains[s.terrain],steps=[],tables=[],fmt=x=>typeof x==='number'?Number(x.toPrecision(12)).toString():String(x),add=(title,formula,substitution,result,unit='',condition='',source='')=>steps.push({title,formula,substitution,result,unit,condition,source});
 tables.push({title:'實際地況來源表與採用列',source:'既有引擎 terrains；規範 §2.3、§2.6、§2.7',headers:['地況','α','zg m','c','ℓ m','ε','zmin m','本次選擇'],rows:Object.entries(terrains).map(([k,v])=>[k,v.alpha,v.zg,v.c,v.ell,v.eps,v.zmin,k===s.terrain?'採用':'未採用'])});
 const qp=(z,label)=>{const ze=Math.max(5,z),k=K(z,t),v=q(z,s);add(label,'ze=max(5,z); K=2.774(ze/zg)^(2α); q=0.06 K Kzt (I V)²',`ze=max(5,${z})=${ze} m; K=2.774(${ze}/${t.zg})^(${2*t.alpha})=${fmt(k)}; q=0.06×${fmt(k)}×${s.kzt}×(${s.I}×${s.V})²`,v,'kgf/m²','所有高度採同一輸入 Kzt；5 m 以下固定；I 在平方內','規範 §2.6；地況表採 '+s.terrain+' 列');};
 if(kind==='building'||kind==='component')qp(s.h,'屋頂風速壓 q(h)');qp(5,'積分基準風速壓 q(5)');
 if(kind==='building'){
 const g=r.g,ratio=s.L/s.B,ends=ratio<=1?[1,-.5,1,-.5]:ratio<=2?[1,-.5,2,-.3]:ratio<4?[2,-.3,4,-.2]:[4,-.2,4,-.2];
 tables.push({title:'背風牆 Cp 來源表及內插端點',source:'既有 cpLeeward 函數；規範表 2.4',headers:['L/B','Cp','本次條件'],rows:[[1,-.5,ratio<=1?'下限定值':''],[2,-.3,ratio>1&&ratio<=2?'1–2 內插':''],[4,-.2,ratio>2&&ratio<4?'2–4 內插':ratio>=4?'上限定值':'']]});
 add('風向與背風係數內插','r=L/B; Cp=Cp₀+(Cp₁−Cp₀)(r−r₀)/(r₁−r₀)',`B=${s.B} m; L=${s.L} m; r=${fmt(ratio)}; 端點 (${ends[0]},${ends[1]})、(${ends[2]},${ends[3]}); ${ends[0]===ends[2]?'採端點定值':`${ends[1]}+(${ends[3]}−${ends[1]})×(${fmt(ratio)}−${ends[0]})/(${ends[2]}−${ends[0]})`}`,r.cp,'','迎風 Cp=0.8；側風 Cp=−0.7；本次方向幾何以 B、L 定義','規範表 2.4');
 add('陣風中間參數','z̄=max(0.6h,zmin); Iz=c(10/z̄)^(1/6); Lz=ℓ(z̄/10)^ε; Q=[1+0.63((B+h)/Lz)^0.63]^−1/2',`z̄=max(0.6×${s.h},${t.zmin})=${fmt(g.zbar)}; Iz=${t.c}(10/${fmt(g.zbar)})^(1/6)=${fmt(g.Iz)}; Lz=${t.ell}(${fmt(g.zbar)}/10)^${t.eps}=${fmt(g.Lz)}; Q=[1+0.63((${s.B}+${s.h})/${fmt(g.Lz)})^0.63]^−1/2`,g.Q,'','固定 G 分支仍計算此組參數，但不採公式 G','規範 §2.7');
 add('實際採用陣風因子',s.gmode==='fixed'?'G=1.88':'G=1.927(1+1.7×3.4 Iz Q)/(1+1.7×3.4 Iz)',s.gmode==='fixed'?'使用者選固定值':`1.927(1+1.7×3.4×${fmt(g.Iz)}×${fmt(g.Q)})/(1+1.7×3.4×${fmt(g.Iz)})`,g.G,'','fn≥1 Hz 的原適用性檢核；不計算柔性 Gf','規範 §2.7');
 const n=2*t.alpha,c=q(5,s)/5**n;
 add('精確積分與 5 m 分段','Iq=∫q dz; Izq=∫zq dz; q(z)=q5(z/5)^n (z>5)',`n=2×${t.alpha}=${n}; c=q5/5^n=${fmt(c)}; 5 m 以下 q5×(u^(m+1)−a^(m+1))/(m+1)；以上 c×(b^(n+m+1)−l^(n+m+1))/(n+m+1)`,c,'kgf/m^(2+n)','m=0 計 Iq，m=1 計 Izq；u=min(b,5)，l=max(a,5)；依實際 a、b 分支','同引擎 integralQ');
 for(const [i,row]of r.rows.entries()){const iq=integralQ(row.a,row.b,0,s),izq=integralQ(row.a,row.b,1,s);qp(row.b,`第 ${i+1} 段頂風速壓`);add(`第 ${i+1} 段積分、風力及力矩`,'F=B G[0.8Iq−Cp qh(b−a)]; M=B G[0.8Izq−Cp qh(b²−a²)/2]; z=M/F',`a=${fmt(row.a)}, b=${fmt(row.b)} m; Iq=${fmt(iq)}, Izq=${fmt(izq)}; qavg=${fmt(iq/(row.b-row.a))}; p=${fmt(row.p)} kgf/m²; F=${s.B}×${fmt(g.G)}×[0.8×${fmt(iq)}−(${r.cp})×${fmt(r.qh)}×${fmt(row.b-row.a)}]=${fmt(row.F)} kgf; M=${fmt(row.M)} kgf·m; z=${fmt(row.M)}/${fmt(row.F)}=${fmt(row.z)} m`,row.F,'kgf','精確積分，沒有逐段先行取整；內壓在等面積迎／背牆順風合力抵消','同引擎 building/ integralQ');}
 add('各段加總與合力高度','V=ΣFi; M=ΣMi; z=M/V',`ΣFi=${r.rows.map(x=>fmt(x.F)).join('+')}; ΣMi=${r.rows.map(x=>fmt(x.M)).join('+')}; z=${fmt(r.M)}/${fmt(r.F)}=${fmt(r.z)}`,r.F,'kgf','風力／力矩轉 tf／tf·m 除 1000；畫面兩位小數，內部未取整');
 for(const face of r.faces)add(face.name+'兩個內壓案例','p=q(h)G Cp−q(h)GCpi',`q(h)=${fmt(r.qh)}, G=${fmt(g.G)}, Cp=${face.cp}; GCpi=−${r.ci}: p=${fmt(face.minus)}; GCpi=+${r.ci}: p=${fmt(face.plus)}`,face.minus,'kgf/m²','兩個全棟內壓案例，不把不同面極值拼成同一荷載案例','規範表 2.17；封閉/部分封閉列');
 add('屋頂 Cp 分支及上吸合力','Cp=−0.7 if h/L≤2.5 and h/B≤2.5 else −0.8; U=−(Cp G−ci)qh BL',`h/L=${fmt(s.h/s.L)}; h/B=${fmt(s.h/s.B)}; Cp=${r.roofCp}; −(${r.roofCp}×${fmt(g.G)}−${r.ci})×${fmt(r.qh)}×${s.B}×${s.L}`,r.roofUplift,'kgf','平屋頂平均力；不是局部屋頂邊角 GCp');
 }else if(kind==='open'){
 qp(s.z,'受風面積形心風速壓');add('人工查表係數來源狀態','Cf 與 Ac 必須使用同一表面積定義',`Cf=${s.cf}; G=${s.G}; Ac=${s.area} m²`,'未提供個案表號、列欄及內插紀錄','','引擎不自動查 Cf／G，不虛構來源列欄','Cf：規範表 2.9–2.16，依結構型式人工查定');add('指定受風部分風力','p=qG Cf; F=pAc',`p=${fmt(r.qc)}×${s.G}×${s.cf}=${fmt(r.p)}; F=${fmt(r.p)}×${s.area}`,r.F,'kgf','未自動修正遮蔽、開放率、端部效應');add('引擎力矩','M=Fz',`${fmt(r.F)}×${s.z}`,r.M,'kgf·m','單斜屋頂原畫面不採此值為水平傾覆力矩；缺傾角與壓力中心時仍不提供水平支承反力');
 }else{
 qp(s.z,'構材高度風速壓');add('局部外壓高度選擇','qe=qh if h≤18 or surface≠windward else q(z)',`h=${s.h} m; 表面=${s.surface}; qi=qh=${fmt(r.qh)}; qe=${fmt(r.qe)}`,r.qe,'kgf/m²','GCp 已含陣風，不再乘 G','規範 §3.2');add('人工查圖來源狀態','GCp 正負分別查圖，受風面積 A 不一定是有效面積',`GCp+=${s.gcpPos}; GCp−=${s.gcpNeg}; A=${s.area} m²`,s.h<=18?'圖 3.1':'圖 3.2','','個案表面區、有效面積、圖上列欄及內插紀錄未提供；不能由程式推定','規範局部構材圖');for(const [i,c]of r.cases.entries())add(`內外壓候選 ${i+1}`,'p=qe GCp−qh GCpi; F=pA',`${fmt(r.qe)}×(${c.cp})−${fmt(r.qh)}×(${c.ci})=${fmt(c.p)}; F=${fmt(c.p)}×${s.area}=${fmt(c.F)}`,c.p,'kgf/m²','正负外壓 × 兩內壓符號');add('候選包絡','pmax=max(pi); pmin=min(pi)',`候選=${r.cases.map(c=>fmt(c.p)).join(', ')}; pmax=${fmt(r.pmax)}; pmin=${fmt(r.pmin)}; Fmax=${fmt(r.pmax*s.area)}, Fmin=${fmt(r.pmin*s.area)} kgf`,r.pmax,'kgf/m²','只包絡本次指定表面區，不宣稱掃描所有建物面区/風向');
 }
 add('數字及單位顯示','1 kgf/m²=0.00980665 kN/m²=0.001 tf/m²; 1 tf=1000 kgf','畫面壓力 kgf 2位、kN 3位、tf 4位；風力/彎矩2位；報告過程12有效位','僅顯示取整','','引擎計算無逐項取整、無新增設計上限');return {steps,tables};
}
