(()=>{'use strict';
const $=id=>document.getElementById(id),E=WindFull,esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=(x,d=4)=>x===null?'不適用':Number(x).toLocaleString('en-US',{maximumFractionDigits:d}),table=(h,rs)=>'<div class="scroll"><table><thead><tr>'+h.map(x=>'<th>'+esc(x)+'</th>').join('')+'</tr></thead><tbody>'+rs.map(r=>'<tr>'+r.map(x=>'<td>'+esc(x)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';
// [id,label,default,options or null,help]. No suggested modal values are used as measured data.
const groups=[['專案與設計情境',[
 ['project','專案名稱','操作示例',null,'輸入案件名稱或施工階段編號；將列於報告。','text'],
 ['stage','設計情境','permanent',{permanent:'永久使用',temporary:'施工期間／臨時支撐'},'施工模式僅適用 §6.2；不可推廣至任意短期活動。'],
 ['T','施工回歸期 T（年）',10,null,'依 §6.2 與專案核定條件填入，最低 10 年；本程式支援 10–50 年內插，不依使用天數直接折減。'],
 ['months','使用期間（月）',6,null,'取施工計畫的實際使用月數；僅列入報告，不自動決定回歸期或折減率。'],
 ['tempBasis','施工回歸期採用依據','',null,'記錄施工用途、期間、設計者選定回歸期及核定文件。例：支撐使用 6 月，採 10 年回歸期，計畫書第…頁。','text']]],
 ['工址風場',[
 ['V','50 年基本風速（m/s）',37.5,null,'地況 C、10 m 高、10 分鐘平均風速。依工址查 §2.4／表 2.21；37.5 僅作操作例。不能輸入瞬間陣風或已折減風速。'],
 ['I','用途係數 I',1,{'.9':'0.9（依 §2.5）','1':'1.0 一般','1.1':'1.1 重要'},'按 §2.5 確定用途。施工模式採 1 或依重要性要求採 1.1；不再疊加低重要性 0.9 折減。'],
 ['tx','X 來風地況','B',{A:'A 都市中心',B:'B 市郊／小市鎮',C:'C 開闊地'},'依上游粗糙度及規範定義判斷，不按行政區名稱選擇。'],
 ['ty','Y 來風地況','B',{A:'A 都市中心',B:'B 市郊／小市鎮',C:'C 開闊地'},'可與 X 方向不同，依該方向上游地物及地況延伸距離判斷。'],
 ['kx','X 地形係數 Kzt',1,null,'一般平地可為 1；山丘、山脊與懸崖依表 2.3。此工具假設全高度固定，特殊風場需另評估。'],
 ['ky','Y 地形係數 Kzt',1,null,'依 Y 方向特殊地形核定；無特殊地形的示例為 1。'],
 ['halfMethod','半年基本風速來源','estimate',{estimate:'依解說 V50／3.34',custom:'輸入有依據的半年值'},'半年回歸期僅用於 §4.3 舒適性，不是短期施工設計回歸期。'],
 ['Vhalf','自訂半年風速（m/s）',11.22754491,null,'需以可靠風速統計或專案報告確定，不得將陣風值當作 10 分鐘平均。'],
 ['halfBasis','半年風速來源','',null,'自訂時必填：統計方法、資料來源及報告版本／頁碼。','text']]],
 ['幾何與適用條件',[
 ['h','屋頂高度 h（m）',20,null,'取建築平屋頂高度；高樓模組僅適用規則矩形柱體，依結構／建築圖。'],
 ['x','X 平面尺寸（m）',30,null,'X 方向來風時為顺風深度 L；Y 方向來風時為迎風寬度 B。取建築外緣尺寸。'],
 ['y','Y 平面尺寸（m）',20,null,'X 方向來風時為迎風寬度 B；由建築圖取得。'],
 ['n','等高分段數',5,null,'無實際樓高資料時的分析帶數量（1–200）；不代表實際樓層勁度。'],
 ['levels','各層頂標高（m，選填）','',null,'依圖面填 4,8,12,16,20；須遞增且末項等於 h。有填則取代等高分段；變位檢核使用此樓層高度。','text'],
 ['shape','建築形狀','regular',{regular:'規則矩形平屋頂柱體',other:'其他形狀／不確定'},'非矩形、退縮、不規則或氣動影響重要者，不自動套用規則柱體完整分析。'],
 ['material','主要結構材料','RC',{RC:'RC',SRC:'SRC',steel:'鋼構',other:'其他'},'由結構圖取得；影響 §4.3 解說的舒適性免檢條件，不推算構件抗力。'],
 ['occupancy','是否有居室','occupied',{occupied:'有居室／未確認',none:'無居室'},'依建築用途確認；無居室僅可能免最高居室加速度檢核，不免強度與穩定。'],
 ['special','周邊干擾／近頻耦合','no',{no:'專案評估無顯著影響',yes:'有／待專案評估'},'需檢視高樓群、氣動耦合、扭轉與平移頻率接近等情形。無法確認時選待評估。']]],
 ['動態參數',[
 ['fx','X 平移頻率（Hz）',1,null,'採模態分析基本自然頻率。高樓範例 0.35 僅教學，不能視為建議設計值。'],
 ['fy','Y 平移頻率（Hz）',1,null,'Y 方向基本模態頻率；X 來風時為橫風頻率 fa，Y 來風時為順風 fn。'],
 ['ft','扭轉頻率（Hz）',1.3,null,'採模型扭轉基本模態頻率，不能以假定值取代核定模態分析。'],
 ['bx','X 結構阻尼比',.01,null,'輸入小數：0.01＝1%。依材料、分析目的與規範／試驗採用；不是 1 表示 1%。'],
 ['by','Y 結構阻尼比',.01,null,'依專案結構與振幅估定之 Y 阻尼；典型示範 0.01，不自動推定實際值。'],
 ['bt','扭轉結構阻尼比',.01,null,'供 RTR／β 計算的結構阻尼；與規範 RTR 公式中的氣動 βT 參數不同。'],
 ['gmode','普通結構 G 選項','fixed',{fixed:'固定 G＝1.88',formula:'§2.7 公式 G'},'fn≥1 Hz 可用普通結構 G；fn<1 時程式自動用 §2.8 Gf，不受此選項影響。']]]];
const fields=groups.flatMap(g=>g[1]),stringIds=new Set(fields.filter(x=>x[5]==='text'||x[3]).map(x=>x[0]));stringIds.delete('I');
$('inputs').innerHTML=groups.map(([name,fs])=>'<details class="card" open><summary>'+name+'</summary><div class="fields">'+fs.map(([id,label,value,options,help,type])=>'<label class="field '+(type==='text'?'wide':'')+'" for="'+id+'">'+label+(options?'<select id="'+id+'">'+Object.entries(options).map(([v,t])=>'<option value="'+v+'"'+(String(value)===v?' selected':'')+'>'+t+'</option>').join('')+'</select>':'<input id="'+id+'" type="'+(type||'number')+'" '+(type==='text'?'maxlength="500"':'step="any"')+' value="'+esc(value)+'">')+'</label>').join('')+'</div></details>').join('');
const external=[['members','構件與接頭'],['stability','整體穩定／二階效應'],['foundation','基礎／錨定'],['cladding','局部構材／外部被覆物']];
$('reviewFields').innerHTML=external.map(([id,label])=>'<h3>'+label+'</h3><div class="check-grid"><label>狀態<select id="'+id+'State"><option value="pending">待檢核</option><option value="checked">已檢核</option><option value="na">有依據不適用</option></select></label><label>最大需求／容量比<input id="'+id+'Ratio" type="number" step="any" min="0"></label><label>方法、規範、模型及報告頁碼<input id="'+id+'Source"></label></div>').join('');
$('fieldGuide').innerHTML=table(['欄位','定義／資料來源'],fields.map(x=>[x[1],x[4]]));
// Definitions remain accessible on focus/touch as well as mouse hover.
let focusedHelp=null;
fields.forEach(([id,label,,opts,help])=>{const e=$(id);e.title=help;e.setAttribute('aria-describedby','tip-'+id);const sr=document.createElement('span');sr.id='tip-'+id;sr.hidden=true;sr.textContent=help;e.after(sr);function show(){const tip=$('tooltip');tip.innerHTML='<strong>'+esc(label)+'</strong><p>'+esc(help)+'</p>';tip.hidden=false;const r=e.getBoundingClientRect();tip.style.left=Math.max(8,Math.min(r.left,innerWidth-tip.offsetWidth-8))+'px';tip.style.top=Math.max(8,Math.min(r.bottom+8,innerHeight-tip.offsetHeight-8))+'px';}e.addEventListener('pointerenter',show);e.addEventListener('focus',()=>{focusedHelp=show;show()});e.addEventListener('pointerleave',()=>$('tooltip').hidden=true);e.addEventListener('blur',()=>{focusedHelp=null;$('tooltip').hidden=true});});window.addEventListener('scroll',()=>{if(focusedHelp)focusedHelp();else $('tooltip').hidden=true},true);document.addEventListener('keydown',e=>{if(e.key==='Escape')$('tooltip').hidden=true});
let result=null,lastFingerprint='',checks={},restoring=false;
const extraIds=['effectsSource','effectsData','driftSource','driftData','occupiedHeight','comfortSource','comfortData','assessment',...external.flatMap(([id])=>[id+'State',id+'Ratio',id+'Source'])];
function read(){return Object.fromEntries(fields.map(([id])=>[id,stringIds.has(id)?$(id).value:Number($(id).value)]));}
function sync(){const temp=$('stage').value==='temporary';['T','months','tempBasis'].forEach(id=>$(id).closest('label').hidden=!temp);if(temp&&Number($('I').value)<1)$('I').value='1';$('I').disabled=false;$('I').querySelector('option[value=".9"]').disabled=temp;['Vhalf','halfBasis'].forEach(id=>$(id).closest('label').hidden=$('halfMethod').value!=='custom');}
function status(t){$('status').textContent=t;}
function tab(id){document.querySelectorAll('[data-pane]').forEach(e=>e.hidden=e.dataset.pane!==id);document.querySelectorAll('[data-tab]').forEach(e=>e.setAttribute('aria-selected',String(e.dataset.tab===id)));document.body.dataset.mobile='result';}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>tab(b.dataset.tab));$('helpBtn').onclick=()=>tab('help');$('mobileInput').onclick=()=>document.body.dataset.mobile='input';$('mobileResult').onclick=()=>document.body.dataset.mobile='result';
function pack(){return{schema:'wind-full',version:2,values:Object.fromEntries(fields.map(([id])=>[id,$(id).value])),analysis:Object.fromEntries(extraIds.map(id=>[id,$(id).value]))};}
function persist(){if(restoring)return;try{localStorage.setItem('wind-full-v2',JSON.stringify(pack()));}catch{} }
function validatePack(p){if(p?.schema!=='wind-full'||p.version!==2||!p.values||!p.analysis)throw Error('不是本模組 v2 專案');for(const id of [...fields.map(x=>x[0]),...extraIds]){const v=id in p.values?p.values[id]:p.analysis[id],el=$(id);if(typeof v!=='string'||v.length>100000)throw Error('欄位錯誤：'+id);if(el.tagName==='SELECT'&&![...el.options].some(x=>x.value===v))throw Error('選項錯誤：'+id);if(el.type==='number'&&v!==''&&!Number.isFinite(Number(v)))throw Error('非數值：'+id);}return p;}
function applyPack(p){validatePack(p);restoring=true;for(const [id,v]of Object.entries({...p.values,...p.analysis}))if($(id))$(id).value=v;checks={};for(const id of ['effects','drift','comfort','review'])$(id+'Result').textContent='已載入資料，請重新檢核。';lastFingerprint='';update();restoring=false;persist();}
function update(){sync();try{for(const [id,,,opts,,type]of fields)if(!opts&&type!=='text'&&!$(id).closest('label').hidden&&$(id).value.trim()==='')throw Error('請完成輸入：'+id);const s=read(),fp=JSON.stringify(s);if(lastFingerprint&&fp!==lastFingerprint){checks={};for(const id of ['effects','drift','comfort','review'])$(id+'Result').textContent='輸入參數已變更；舊分析資料尚未重新確認。';}lastFingerprint=fp;result=E.analyze(s);$('error').hidden=true;render();$('word').disabled=false;$('offline').disabled=false;$('csv').disabled=result.design.some(d=>!d.valid);}catch(e){result=null;checks={};$('error').textContent=e.message;$('error').hidden=false;['metrics','summary','loadTables','warnings'].forEach(id=>$(id).innerHTML='');for(const id of ['effects','drift','comfort','review'])$(id+'Result').textContent='參數無效，不能採用舊結果。';$('word').disabled=$('offline').disabled=$('csv').disabled=true;}reviewStatus();persist();}
function render(){const r=result,s=r.s;const name=s.stage==='temporary'?'施工期 '+s.T+' 年回歸期／使用 '+s.months+' 月':'永久使用／50 年基本風速';$('scenario').textContent=name+' · V50＝'+fmt(s.V)+' m/s → 本案基本風速 '+fmt(r.V)+' m/s · 風速比 '+fmt(r.factor,6)+' · I＝'+s.I;$('title').textContent=s.project||'順風、橫風與扭轉';$('warnings').innerHTML=[...r.warnings,...r.design.flatMap(d=>d.blocks.map(x=>d.axis+'：'+x))].map(x=>'<div class="notice">'+esc(x)+'</div>').join('');$('metrics').innerHTML=[['X 來風順風剪力',r.design[0].total.D/1000,'tf'],['Y 來風順風剪力',r.design[1].total.D/1000,'tf'],['兩風向扭矩包絡',r.design.every(d=>d.valid)?Math.max(...r.design.map(d=>d.total.T))/1000:null,'tf·m']].map(([label,v,u])=>'<div class="metric"><small>'+label+'</small><strong>'+fmt(v)+' <small>'+u+'</small></strong></div>').join('');$('summary').innerHTML=table(['來風','B / L (m)','h/√BL','fn / fa / ft (Hz)','G 或 Gf','順風 D (tf)','橫風 L (tf)','扭矩 T (tf·m)','D 彎矩 (tf·m)','L 彎矩 (tf·m)'],r.design.map(d=>[d.axis,fmt(d.B)+' / '+fmt(d.L),fmt(d.slender),d.f+' / '+d.fa+' / '+s.ft,d.g.kind+' '+fmt(d.g.G),fmt(d.total.D/1000),fmt(d.valid?d.total.L/1000:null),fmt(d.valid?d.total.T/1000:null),fmt(d.total.DM/1000),fmt(d.valid?d.total.LM/1000:null)]))+'<h3>動態中間量（可追溯）</h3>'+table(['來風','qh kgf/m²','Vz m/s','Vh m/s','Iz','Q','R','gR','Ua','Ut','RLR','RTR'],r.design.map(d=>[d.axis,...[d.qh,d.g.Vz,d.Vh,d.g.Iz,d.g.Q,d.g.R,d.g.g,d.Ua,d.Ut,d.rlr,d.rtr].map(x=>fmt(x,6))]));$('exempt').textContent=r.exempt?'按目前材料、用途、高寬比及地況，符合 §4.3 解說的加速度免檢條件；可自願進一步檢核。':'本案不符合預設免檢條件，須填寫半年共振分析結果。';renderLoads();}
const loadHeaders=['來風','層','底 m','頂 m','D kgf','D平均 kgf','L kgf','T kgf·m','DM kgf·m','LM kgf·m','D合力高 m','L合力高 m','樓層剪力D kgf','樓層剪力L kgf','樓層扭矩T kgf·m'];
function loadRows(ds){return ds.flatMap(d=>d.rows.map(r=>[d.axis,r.level,r.a,r.b,r.D,r.mean,r.L,r.T,r.DM,r.LM,r.DM/r.D,r.L===null?null:r.LM/r.L,r.storyD,r.storyL,r.storyT]));}
function renderLoads(){if(!result)return;const k=$('loadPeriod').value,ds=result[k];$('loadNote').textContent=k==='half'?'半年 V＝'+fmt(result.halfV)+' m/s；D、L、T 為僅共振分量。D平均欄不適用並輸出 0。':k==='drift'?'50 年基本風速、I＝1，用於 §4.2 變位檢核；不使用施工折減。':'本案設計情境：'+$('scenario').textContent;$('loadTables').innerHTML=table(loadHeaders,loadRows(ds).map(row=>row.map((x,i)=>i===5&&k==='half'?0:typeof x==='number'?fmt(x,5):x)));$('csv').disabled=ds.some(d=>!d.valid);}
$('loadPeriod').onchange=renderLoads;
function ensure(){if(!result)throw Error('請先完成有效參數');if(result.design.some(d=>!d.valid))throw Error('本案不符合自動完整分析適用範圍，需專案／風洞分析');}
function lines(id,n){const txt=$(id).value.trim();if(!txt)throw Error('尚未填寫分析數據');return txt.split(/\r?\n/).filter(x=>x.trim()).map((line,i)=>{const v=line.split(',').map(x=>x.trim());if(v.length!==n)throw Error('第 '+(i+1)+' 列應有 '+n+' 欄；不要加標題列或引號');if(!['X','Y'].includes(v[0]))throw Error('來風須為 X 或 Y');return v;});}
function numeric(v){if(v===''||!Number.isFinite(Number(v)))throw Error('缺值或非有限數字');return Number(v);}
function source(id){if(!$(id+'Source').value.trim())throw Error('請填寫分析來源及適用案例');}
function runCheck(id,fn){try{ensure();const out=fn();checks[id]={...out,fingerprint:lastFingerprint};$(id+'Result').innerHTML=out.html;status('已更新 '+id+' 檢核；確認來源確實對應本次參數。');}catch(e){delete checks[id];$(id+'Result').innerHTML='<p class="bad">'+esc(e.message)+'</p>';}reviewStatus();persist();}
$('effectsCheck').onclick=()=>runCheck('effects',()=>{source('effects');const rows=lines('effectsData',7).map(v=>{if(!v[1]||!v[2])throw Error('效應名稱與單位必填');const c=E.combine(...v.slice(3).map(numeric));return[...v,fmt(c.max,6),fmt(c.min,6),fmt(c.abs,6)]});return{pass:true,rows,html:table(['來風','構件效應','單位','D平均','D峰值','L峰值','T峰值','W+','W−','絕對包絡'],rows)+'<p>已組合 '+rows.length+' 列。須由設計者確認已涵蓋所有控制效應與兩風向；本表不比較構件抗力。</p>'};});
$('driftCheck').onclick=()=>runCheck('drift',()=>{source('drift');if(result.drift.some(d=>!d.valid))throw Error('50 年載重超出自動分析範圍');const heights=E.heights(result.s),seen=new Set();let pass=true;const rows=lines('driftData',6).map(v=>{const level=numeric(v[1]);if(!Number.isInteger(level)||level<1||level>heights.length)throw Error('樓層序號不符');const key=v[0]+level;if(seen.has(key))throw Error('重複風向／樓層');seen.add(key);const dh=heights[level-1]-(heights[level-2]||0),c=E.combine(...v.slice(2).map(numeric)),ratio=c.abs/dh,ok=ratio<=.005;pass&&=ok;return[v[0],level,dh,fmt(c.abs,7),fmt(ratio,7),ok?'符合':'超限']});if(seen.size!==2*heights.length)throw Error('資料不完整：需 '+(2*heights.length)+' 列（每層 X、Y），目前 '+seen.size+' 列');return{pass,rows,html:table(['來風','層','層高 m','最大相對位移 m','變位角','≤0.005'],rows)};});
$('comfortCheck').onclick=()=>runCheck('comfort',()=>{source('comfort');if(result.half.some(d=>!d.valid))throw Error('半年載重超出自動分析範圍');const occupied=numeric($('occupiedHeight').value);if(occupied<=0||occupied>result.s.h)throw Error('最高居室標高須 >0 且 ≤h');const seen=new Set();let pass=true;const rows=lines('comfortData',4).map(v=>{if(seen.has(v[0]))throw Error('重複風向');seen.add(v[0]);const d=result.half.find(d=>d.axis===v[0]),a=E.acceleration(d.B,d.L,d.f,d.fa,result.s.ft,...v.slice(1).map(numeric));pass&&=a.pass;return[v[0],...v.slice(1),fmt(a.AD,7),fmt(a.AL,7),fmt(a.AT,7),fmt(a.A,7),a.pass?'符合':'超限']});if(seen.size!==2)throw Error('需要 X、Y 兩方向分析資料');return{pass,rows,html:table(['來風','D* m','L* m','θ* rad','AD m/s²','AL m/s²','AT rad/s²','A m/s²','≤0.05'],rows)};});
$('reviewCheck').onclick=()=>runCheck('review',()=>{let pass=true;const rows=external.map(([id,label])=>{const st=$(id+'State').value,src=$(id+'Source').value.trim();if(st==='pending'||!src)throw Error(label+' 尚未完成或缺少依據');const v=st==='checked'?numeric($(id+'Ratio').value):null;if(v!==null&&v<0)throw Error(label+' 容量比不得為負');const ok=st==='na'||v<=1;pass&&=ok;return[label,st==='na'?'有依據不適用':fmt(v,6),src,ok?'紀錄符合':'超限']});if(!$('assessment').value.trim())throw Error('請填寫適用性／風洞評估結論及報告來源');return{pass,rows,html:table(['項目','需求／容量比','依據','紀錄'],rows)+'<p>以上為外部檢核紀錄，尚須與原始分析報告核對。</p>'};});
function reviewStatus(){const rows=[['風載適用性',result&&result.design.every(d=>d.valid)?'適用範圍內':'待確認／不適用'],['§2.12 效應組合',checks.effects?'已組合輸入項目':'待填模型效應'],['§4.2 變位',checks.drift?(checks.drift.pass?'已填且符合':'超限'):'待檢核'],['§4.3 加速度',checks.comfort?(checks.comfort.pass?'已填且符合':'超限'):result?.exempt?'符合免檢條件':'待檢核'],['外部設計報告',checks.review?(checks.review.pass?'已填符合紀錄':'有超限項目'):'待檢核']];const complete=result&&result.design.every(d=>d.valid)&&checks.effects&&checks.drift?.pass&&(checks.comfort?checks.comfort.pass:result.exempt)&&checks.review?.pass;$('reviewStatus').innerHTML='<div class="notice">'+(complete?'指定項目已填寫且通過程式比較，請由設計者核對外部報告並完成簽認。':'整體設計未完成：請補齊待檢核項目，或處理超限／適用性問題。')+'</div>'+table(['檢核項目','目前狀態'],rows);}
extraIds.forEach(id=>$(id).addEventListener('input',()=>{const type=id.startsWith('effects')?'effects':id.startsWith('drift')?'drift':id.startsWith('comfort')||id==='occupiedHeight'?'comfort':'review';delete checks[type];$(type+'Result').textContent='資料已修改，請重新檢核。';reviewStatus();persist();}));
$('inputs').addEventListener('submit',e=>e.preventDefault());$('inputs').addEventListener('input',update);$('inputs').addEventListener('change',update);
function sample(high=false,temp=false){for(const [id,,v]of fields)$(id).value=String(v);if(high)Object.entries({h:100,x:25,y:25,n:25,tx:'C',ty:'C',fx:.35,fy:.35,ft:.6,project:'100 m 高樓操作範例'}).forEach(([id,v])=>$(id).value=String(v));if(temp)Object.entries({stage:'temporary',T:10,months:6,tempBasis:'操作示例：施工支撐，採最低 10 年回歸期，實案另核定',project:'施工 6 個月／10 年回歸期操作範例'}).forEach(([id,v])=>$(id).value=String(v));extraIds.forEach(id=>$(id).value=id.endsWith('State')?'pending':'');checks={};['effects','drift','comfort','review'].forEach(id=>$(id+'Result').textContent='');lastFingerprint='';update();tab('overview');status('已載入教學範例；模態、風速及施工回歸期須依實案確認。');}
$('low').onclick=()=>sample();$('high').onclick=()=>sample(true);$('shortSample').onclick=()=>sample(false,true);
function download(content,name,type){const a=document.createElement('a'),u=URL.createObjectURL(new Blob([content],{type}));a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),2000);}
$('save').onclick=()=>download(JSON.stringify(pack(),null,2),'耐風完整分析專案.json','application/json');$('load').onclick=()=>$('file').click();$('file').onchange=async()=>{try{const f=$('file').files[0];if(!f)return;if(f.size>1500000)throw Error('專案檔過大');applyPack(JSON.parse(await f.text()));status('專案已載入；分析結果需重新檢核確認。');}catch(e){status('未載入：'+e.message)}$('file').value='';};
$('csv').onclick=()=>{try{ensure();const k=$('loadPeriod').value,ds=result[k];if(ds.some(d=>!d.valid))throw Error('所選載重不適用');const rows=loadRows(ds).map(r=>r.map((x,i)=>i===5&&k==='half'?0:x));const quote=x=>'"'+String(x??'').replace(/"/g,'""')+'"';download('\ufeff'+[loadHeaders,...rows].map(r=>r.map(quote).join(',')).join('\r\n'),'wind-'+k+'-'+(result.s.stage==='temporary'?result.s.T:50)+'yr.csv','text/csv;charset=utf-8');}catch(e){status(e.message)}};
function snapshot(){if(!result)throw Error('請先完成有效參數');const s=result.s;const tables=[...['design','drift','half'].map(k=>({title:{design:'本案設計風載',drift:'50 年变位風載',half:'半年僅共振風載'}[k],headers:loadHeaders,rows:loadRows(result[k]).map(r=>r.map((v,i)=>k==='half'&&i===5?0:v)),source:'§§2.6–2.12、4.2–4.4；單位見表頭'}))];for(const [key,c]of Object.entries(checks))tables.push({title:key+' 回填檢核',headers:{effects:['來風','效應','單位','D平均','D峰值','L峰值','T峰值','W+','W−','包絡'],drift:['來風','層','層高','位移','變位角','判定'],comfort:['來風','D*','L*','θ*','AD','AL','AT','A','判定'],review:['項目','容量比','依據','紀錄']}[key],rows:c.rows});return{title:'整體耐風與施工期間分析計算書',valid:true,stale:false,summary:$('scenario').textContent,inputs:[...fields.map(([id,label])=>({label,value:$(id).value,unit:''})),...extraIds.filter(id=>$(id).value).map(id=>({label:$(id).closest('label')?.childNodes[0]?.textContent?.trim()||id,value:$(id).value,unit:''}))],steps:[{title:'短期風速換算／§6.2',formula:'V(T)=V50 × r(T)，10年 r=.782、25年 r=.908、50年 r=1；分段線性內插',substitution:'V50='+s.V+', T='+(s.stage==='temporary'?s.T:50)+', r='+result.factor,result:result.V,unit:'m/s',condition:s.stage==='temporary'?s.tempBasis:'永久使用',source:'國土署《建築物耐風設計規範及解說》§6.2'},...result.design.map(d=>({title:d.axis+' 向動態與幾何參數',formula:'依 §§2.7–2.11；RLR/RTR 按公式計算',substitution:JSON.stringify({B:d.B,L:d.L,a:d.slender,Vh:d.Vh,Vz:d.g.Vz,Iz:d.g.Iz,Q:d.g.Q,R:d.g.R,G:d.g.G,Ua:d.Ua,Ut:d.Ut,RLR:d.rlr,RTR:d.rtr}),result:d.valid?'自動風載適用':d.blocks.join('；'),unit:'',condition:'規則矩形柱體；逐高度帶積分',source:'國土署第二章'}))],tables,conclusions:[$('reviewStatus').textContent,...result.warnings,...result.design.flatMap(d=>d.blocks),'外部資料由使用者提供；程式沒有計算材料抗力或基礎容量。風洞與其他荷載組合依專案報告。','官方來源：https://www.nlma.gov.tw/ch/legislation/regsearch/166']};}
window.windFullSnapshot=snapshot;window.windFullPack=pack;window.windFullResult=()=>result;window.windFullChecks=()=>checks;
$('word').onclick=async()=>{try{await CalculationDocx.download(snapshot(),'整體耐風計算書.docx');status('Word 計算書已匯出，包含情境、來源與檢核狀態。');}catch(e){status(e.message)}};
$('offline').onclick=async()=>{try{if(!result)throw Error('請先完成有效輸入');status('正在打包離線 HTML 與影片…');let src=$('video').getAttribute('src');if(!src.startsWith('data:')){const response=await fetch($('video').src);if(!response.ok)throw Error('影片取得失敗');const b=await response.blob();src=await new Promise((resolve,reject)=>{const f=new FileReader();f.onload=()=>resolve(f.result);f.onerror=reject;f.readAsDataURL(b);});}const clone=document.documentElement.cloneNode(true);clone.querySelector('#seed')?.remove();clone.querySelector('#video').setAttribute('src',src);clone.querySelector('#videoDialog').removeAttribute('open');clone.querySelector('#inputs').innerHTML='';clone.querySelector('#reviewFields').innerHTML='';clone.querySelector('#tooltip').hidden=true;const seed=document.createElement('script');seed.id='seed';seed.type='application/json';seed.textContent=JSON.stringify(pack()).replace(/</g,'\\u003c');clone.querySelector('head').appendChild(seed);download('<!doctype html>'+clone.outerHTML,'整體耐風與施工期間離線版.html','text/html;charset=utf-8');status('離線版已下載，含影片與目前專案；回填資料開啟後須重新檢核。');}catch(e){status('未產生離線檔：'+e.message)}};
const chapterNames=['選擇模組與範例','工址與動態參數','施工期間設定','三向風載與 CSV','效應組合與變位','半年加速度','設計紀錄與報告','離線與手機使用'];$('chapters').innerHTML=chapterNames.map((x,i)=>'<button data-seek="'+i*15+'">'+(i+1)+' '+x+'</button>').join('');$('chapters').querySelectorAll('button').forEach(b=>b.onclick=()=>{const v=$('video'),seek=()=>{v.currentTime=Number(b.dataset.seek);v.play().catch(()=>{});};if(v.readyState>=1)seek();else{v.addEventListener('loadedmetadata',seek,{once:true});v.load();}});$('movie').onclick=()=>$('videoDialog').showModal();$('closeVideo').onclick=()=>$('videoDialog').close();$('videoDialog').addEventListener('close',()=>$('video').pause());
try{const saved=$('seed')?.textContent||localStorage.getItem('wind-full-v2');if(saved){applyPack(JSON.parse(saved));status('已還原設定；結構分析資料須重新確認及檢核。');}else update();}catch(e){update();status('未還原舊設定：'+e.message);}tab('overview');
})();
