/* Taiwan Wind Code 103: §§2.6–2.12, 4.2–4.4, 5.1, 6.2. Units: m, s, kgf. */
(function(root){'use strict';
const terrains={A:{alpha:.32,zg:500,b:.45,c:.45,ell:55,eps:.5,zmin:18},B:{alpha:.25,zg:400,b:.62,c:.30,ell:98,eps:.33,zmin:9},C:{alpha:.15,zg:300,b:.94,c:.20,ell:152,eps:.20,zmin:4.5}};
function positive(v,name,min=0,max=Infinity){if(!Number.isFinite(v)||v<=min||v>max)throw Error(name+'超出範圍');return v;}
function shortFactor(T){if(!Number.isFinite(T)||T<10||T>50)throw Error('施工回歸期須為 10–50 年；不外插');return T<=25?.782+(T-10)/15*(.908-.782):.908+(T-25)/25*(1-.908);}
function q(z,t,V,I=1,kzt=1){return .06*2.774*(Math.max(5,z)/t.zg)**(2*t.alpha)*kzt*(I*V)**2;}
function integralQ(a,b,t,V,I,kzt,moment=0){const p=2*t.alpha,C=.06*2.774*kzt*(I*V)**2/t.zg**p;let out=0;if(a<5){const end=Math.min(b,5);out+=C*5**p*(end**(moment+1)-a**(moment+1))/(moment+1);}if(b>5){a=Math.max(a,5);out+=C*(b**(p+moment+1)-a**(p+moment+1))/(p+moment+1);}return out;}
function peak(f){positive(f,'頻率',1/3600);const a=Math.sqrt(2*Math.log(3600*f));return a+.577/a;}
function spatial(eta){return eta<1e-4?1-2*eta/3+eta*eta/3:1/eta+Math.expm1(-2*eta)/(2*eta*eta);}
function gust(h,B,L,t,V,f,beta,fixed){const z=Math.max(.6*h,t.zmin),Iz=t.c*(10/z)**(1/6),Lz=t.ell*(z/10)**t.eps,Q=Math.sqrt(1/(1+.63*((B+h)/Lz)**.63)),Vz=t.b*(z/10)**t.alpha*V,N=f*Lz/Vz,Rn=7.47*N/(1+10.3*N)**(5/3),Rh=spatial(4.6*f*h/Vz),RB=spatial(4.6*f*B/Vz),RL=spatial(15.4*f*L/Vz),R=Math.sqrt(Rn*Rh*RB*(.53+.47*RL)/beta),g=peak(f),den=1+1.7*3.4*Iz,Gordinary=fixed?1.88:1.927*(1+1.7*3.4*Iz*Q)/den,Gf=1.927*(1+1.7*Iz*Math.hypot(3.4*Q,g*R))/den,Gres=1.927*1.7*Iz*g*R/den;return{z,Iz,Lz,Q,Vz,N,Rn,Rh,RB,RL,R,g,Gordinary,Gf,Gres,G:f<1?Gf:Gordinary,kind:f<1?'Gf':'G'};}
function crossRes(r,n){const beta1=(r**4+2.3*r*r)/(2.4*r**4-9.2*r**3+18*r*r+9.5*r-.15)+.12/r,beta2=.28*r**(-.34),n1=.12/(1+.38*r*r)**.89,n2=.56/r**.85;const term=(k,b,nj)=>k*(1+.6*b)*b*(n/nj)**2/((1-(n/nj)**2)**2+4*b*b*(n/nj)**2);return term(.85,beta1,n1)+(r>=3?term(.02,beta2,n2):0);}
function torsionRes(r,U){const geometry=r*(1+r*r)**2/Math.max(1,r)**2;
 const endpoint=u=>{const low=u<=4.5,K=low?(-1.1*r+.97)/(r*r+.85*r+3.3)+.17:(.077*r-.16)/(r*r-.96*r+.42)+.35/r+.095,b=low?(r+3.6)/(r*r-5.1*r+9.1)+.14/r+.14:(.44*r*r-.0064)/(r**4-.26*r*r+.1)+.2;return .036*K*K*u**(2*b)*geometry;};
 if(U<=4.5||U>=6)return endpoint(U);const a=endpoint(4.5),b=endpoint(6);return a*Math.exp(3.48*Math.log(b/a)*Math.log(U/4.5));}
function cp(r){return r<=1?-.5:r<=2?-.5+.2*(r-1):r<=4?-.3+.05*(r-2):-.2;}
function heights(s){if(s.levels?.trim()){const a=s.levels.trim().split(/[\s,，]+/).map(Number);if(a.length>200||a.some((x,i)=>!Number.isFinite(x)||x<=0||(i&&x<=a[i-1]))||Math.abs(a.at(-1)-s.h)>1e-6)throw Error('樓層高度須逐層增加，末項等於 h，最多 200 層');return a;}if(!Number.isInteger(s.n)||s.n<1||s.n>200)throw Error('分段數須為 1–200 整數');return Array.from({length:s.n},(_,i)=>(i+1)*s.h/s.n);}
function check(s){for(const k of ['h','x','y','V','I','fx','fy','ft','bx','by','bt'])positive(s[k],k);if(s.h>Math.min(terrains[s.tx]?.zg||0,terrains[s.ty]?.zg||0))throw Error('高度超出所選地況梯度高度');if([s.bx,s.by,s.bt].some(x=>x>.2))throw Error('阻尼比請輸入小數，例如 0.01，不能輸入 1 表示 1%');if([s.fx,s.fy,s.ft].some(x=>x<=1/3600))throw Error('頻率不適用尖峰因子公式');if(!['A','B','C'].includes(s.tx)||!['A','B','C'].includes(s.ty))throw Error('地況無效');if(s.kx<1||s.ky<1||!Number.isFinite(s.kx+s.ky))throw Error('地形係數不得小於 1');if(s.stage==='temporary'){shortFactor(s.T);positive(s.months,'施工月數');if(!s.tempBasis?.trim())throw Error('請填寫施工期間及回歸期採用依據');if(s.I<1)throw Error('施工回歸期已折減風速，請勿再疊加 I<1；一般採 1，重要性要求可採 1.1');}return s;}
function direction(s,axis,V,I,period,resonance=false){const X=axis==='X',B=X?s.y:s.x,L=X?s.x:s.y,t=terrains[X?s.tx:s.ty],k=X?s.kx:s.ky,f=X?s.fx:s.fy,fa=X?s.fy:s.fx,beta=X?s.bx:s.by,ba=X?s.by:s.bx,ratio=L/B,slender=s.h/Math.sqrt(B*L),g=gust(s.h,B,L,t,V,f,beta,s.gmode==='fixed'),Vh=1.666*V*(s.h/t.zg)**t.alpha,Ua=Vh/(fa*Math.sqrt(B*L)),Ut=Vh/(s.ft*Math.sqrt(B*L)),nstar=fa*B/Vh,rlr=crossRes(ratio,nstar),rtr=torsionRes(ratio,Ut),CL=.0082*ratio**3-.071*ratio**2+.22*ratio,CT=(.0066+.015*ratio**2)**.78,gl=peak(fa),gt=peak(s.ft),qh=q(s.h,t,V,I,k),G=resonance?g.Gres:g.G;
 const blocks=[];if(s.shape!=='regular')blocks.push('非規則矩形平屋頂：需專案分析或風洞資料');if(slender>6)blocks.push('h/√BL > 6：橫風與扭矩公式不適用');if(slender>=3&&(ratio<.2||ratio>5))blocks.push('3≤h/√BL≤6 時須 0.2≤L/B≤5');if(slender>=3&&Ua>10)blocks.push('橫風無因次風速 > 10');if(slender>=3&&Ut>10)blocks.push('扭轉無因次風速 > 10');const valid=!blocks.length;
 let prev=0;const rows=heights(s).map((z,i)=>{const a=prev,b=z,dz=b-a,zc=(a+b)/2;prev=z;const base=B*(.8*integralQ(a,b,t,V,I,k)-cp(ratio)*qh*dz),D=base*G,DM=B*G*(.8*integralQ(a,b,t,V,I,k,1)-cp(ratio)*qh*(b*b-a*a)/2),mean=base/1.128,Lforce=slender<3?.87*ratio*D*(resonance?.84:1):3*qh*CL*B*dz*zc/s.h*gl*Math.sqrt((resonance?0:1)+rlr/ba),Lm=slender<3?.87*ratio*DM*(resonance?.84:1):3*qh*CL*B/s.h*gl*Math.sqrt((resonance?0:1)+rlr/ba)*(b**3-a**3)/3,Tforce=slender>=3?1.8*qh*CT*B*B*dz*zc/s.h*gt*Math.sqrt((resonance?0:1)+rtr/s.bt):0;return{level:i+1,a,b,z:zc,area:B*dz,D,DM,mean,L:valid?Lforce:null,LM:valid?Lm:null,T:valid?Tforce:null};});
 return{axis,B,L,t,k,f,fa,beta,ba,ratio,slender,g,V,Vh,Ua,Ut,rlr,rtr,CL,CT,gl,gt,qh,cp:cp(ratio),rows,blocks,valid,period,resonance};}
function pair(s,V,I,period,resonance=false){const dirs=[direction(s,'X',V,I,period,resonance),direction(s,'Y',V,I,period,resonance)];if(dirs[0].slender<3){ // Low-rise torsion uses the larger B*WD at EACH strip across wind directions.
 let totalDirs=dirs;if(resonance)totalDirs=[direction(s,'X',V,I,period,false),direction(s,'Y',V,I,period,false)];
 dirs.forEach(d=>d.rows.forEach((r,i)=>{if(!d.valid)return;r.T=.28*Math.max(...totalDirs.map(a=>a.B*a.rows[i].D))*(resonance?.80:1);if(resonance){r.L=.84*.87*d.ratio*totalDirs.find(a=>a.axis===d.axis).rows[i].D;r.LM=.84*.87*d.ratio*totalDirs.find(a=>a.axis===d.axis).rows[i].DM;}}));}
 dirs.forEach(d=>{d.total=Object.fromEntries(['D','DM','L','LM','T','mean'].map(k=>[k,d.rows.some(r=>r[k]===null)?null:d.rows.reduce((n,r)=>n+r[k],0)]));let D=0,L=0,T=0;d.rows.slice().reverse().forEach(r=>{D+=r.D;L+=r.L||0;T+=r.T||0;r.storyD=D;r.storyL=d.valid?L:null;r.storyT=d.valid?T:null;});});return dirs;}
function combine(mean,peakD,L,T){[mean,peakD,L,T].forEach(v=>{if(!Number.isFinite(v))throw Error('組合效應含非數值')});const dyn=Math.hypot(peakD-mean,Math.abs(L)+Math.abs(T));return{mean,dynamic:dyn,max:mean+dyn,min:mean-dyn,abs:Math.abs(mean)+dyn};}
function comfortExempt(s){const a=s.h/Math.sqrt(s.x*s.y);return s.occupancy==='none'||(['RC','SRC'].includes(s.material)&&a<3&&s.h<=70)||(s.material==='steel'&&a<3&&s.h<=70&&s.tx!=='C'&&s.ty!=='C')||(s.material==='steel'&&a<2&&s.h<=40);}
function acceleration(B,L,fn,fa,ft,D,Lstar,theta){[D,Lstar,theta].forEach(v=>{if(!Number.isFinite(v)||v<0)throw Error('半年共振位移須為非負值')});const AD=(2*Math.PI*fn)**2*D,AL=(2*Math.PI*fa)**2*Lstar,AT=(2*Math.PI*ft)**2*theta,A=Math.sqrt(AD*AD+AL*AL+AT*AT*(B*B+L*L)/4+L*AL*AT);return{AD,AL,AT,A,limit:.05,ratio:A/.05,pass:A<=.05};}
function analyze(s){check(s);const factor=s.stage==='temporary'?shortFactor(s.T):1,V=s.V*factor;const design=pair(s,V,s.I,s.stage==='temporary'?s.T:50),drift=pair(s,s.V,1,50),halfV=s.halfMethod==='custom'?positive(s.Vhalf,'半年基本風速'):s.V/3.34;if(s.halfMethod==='custom'&&!s.halfBasis?.trim())throw Error('自訂半年風速需來源');const half=pair(s,halfV,1,.5,true);const warnings=[];if(s.h>100)warnings.push('§5.1：高度超過 100 m，建議進行風洞試驗');if(design.some(d=>d.slender>=4&&d.Ua>8.3))warnings.push('§2.10：需進一步檢核渦散共振／空氣動力不穩定，必要時風洞試驗');if(s.special==='yes')warnings.push('鄰近地物、特殊地形或氣動耦合需專案評估／風洞試驗');if(s.kx!==1||s.ky!==1)warnings.push('本模式 q 採輸入的全高度 Kzt；Vh 與 Vz 按規範基本風速公式，特殊地形的風場及動態效應需專案核對');if(s.stage==='temporary')warnings.push('施工期風載僅供施工狀態；50 年變位及半年舒適性另列，不能以施工折減風載替代永久使用設計');return{s,factor,V,design,drift,half,halfV,warnings,exempt:comfortExempt(s)};}
const api={terrains,shortFactor,q,integralQ,peak,spatial,gust,crossRes,torsionRes,cp,heights,check,direction,pair,combine,acceleration,comfortExempt,analyze};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.WindFull=Object.freeze(api);
})(typeof globalThis==='undefined'?this:globalThis);
